title: 泥人游戏
subtitle: niren game
domain: niren.org
rss: http://niren.org/atom.xml
ga: UA-2922788-2
disqus_shortname: reedhong
comment: 
markdown: rdiscount
pygments: true
regeneration: true
lsi: true
permalink: /blog/:year/:month/:day/:title/
category_dir: ../blog/categories/
tag_dir: ../blog/tags/
tag_title_prefix: 'Tag: '
